/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Account: typeof import('./../src/components/account.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPageHeader: typeof import('element-plus/es')['ElPageHeader']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElStep: typeof import('element-plus/es')['ElStep']
    ElSteps: typeof import('element-plus/es')['ElSteps']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElText: typeof import('element-plus/es')['ElText']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    HaiUserCardV2: typeof import('./../src/components/user/HaiUserCardV2.vue')['default']
    HamiAccountSetting: typeof import('./../src/components/account/HamiAccountSetting.vue')['default']
    HamiCommonSetting: typeof import('./../src/components/account/HamiCommonSetting.vue')['default']
    HamiCreatorHome: typeof import('./../src/components/creator/HamiCreatorHome.vue')['default']
    HamiEye: typeof import('./../src/components/icon/HamiEye.vue')['default']
    HamiEyeIcon: typeof import('./../src/components/icon/HamiEyeIcon.vue')['default']
    HamiHeader: typeof import('./../src/components/common/HamiHeader.vue')['default']
    HamiLikeIcon: typeof import('./../src/components/icon/HamiLikeIcon.vue')['default']
    HamiLoading: typeof import('./../src/components/common/HamiLoading.vue')['default']
    HamiLoginCard: typeof import('./../src/components/auth/HamiLoginCard.vue')['default']
    HamiLoginRecord: typeof import('./../src/components/account/HamiLoginRecord.vue')['default']
    HamiLoginRegister: typeof import('./../src/components/auth/HamiLoginRegister.vue')['default']
    HamiLogo: typeof import('./../src/components/common/HamiLogo.vue')['default']
    HamiRegisterCard: typeof import('./../src/components/auth/HamiRegisterCard.vue')['default']
    HamiResetPasswordCard: typeof import('./../src/components/auth/HamiResetPasswordCard.vue')['default']
    HamiRestPasswordCard: typeof import('./../src/components/auth/HamiRestPasswordCard.vue')['default']
    HamiSetting: typeof import('./../src/components/account/HamiSetting.vue')['default']
    HamiUserCardV1: typeof import('./../src/components/user/HamiUserCardV1.vue')['default']
    HamiUserCardV2: typeof import('./../src/components/user/HamiUserCardV2.vue')['default']
    HamiUserCardV3: typeof import('./../src/components/user/HamiUserCardV3.vue')['default']
    HamiUserProfile: typeof import('./../src/components/account/HamiUserProfile.vue')['default']
    HeaderAvatar: typeof import('./../src/components/common/HeaderAvatar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UpdatePassForm: typeof import('./../src/components/account/UpdatePassForm.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
