/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElStep: typeof import('element-plus/es')['ElStep']
    ElSteps: typeof import('element-plus/es')['ElSteps']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    HamiEye: typeof import('./../src/components/icon/HamiEye.vue')['default']
    HamiLoginCard: typeof import('./../src/components/auth/HamiLoginCard.vue')['default']
    HamiLoginRegister: typeof import('./../src/components/auth/HamiLoginRegister.vue')['default']
    HamiRegisterCard: typeof import('./../src/components/auth/HamiRegisterCard.vue')['default']
    HamiResetPasswordCard: typeof import('./../src/components/auth/HamiResetPasswordCard.vue')['default']
    HamiRestPasswordCard: typeof import('./../src/components/auth/HamiRestPasswordCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
