/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPageHeader: typeof import('element-plus/es')['ElPageHeader']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElStep: typeof import('element-plus/es')['ElStep']
    ElSteps: typeof import('element-plus/es')['ElSteps']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    HamiEye: typeof import('./../src/components/icon/HamiEye.vue')['default']
    HamiHeader: typeof import('./../src/components/common/HamiHeader.vue')['default']
    HamiLoginCard: typeof import('./../src/components/auth/HamiLoginCard.vue')['default']
    HamiLoginRegister: typeof import('./../src/components/auth/HamiLoginRegister.vue')['default']
    HamiLogo: typeof import('./../src/components/common/HamiLogo.vue')['default']
    HamiRegisterCard: typeof import('./../src/components/auth/HamiRegisterCard.vue')['default']
    HamiResetPasswordCard: typeof import('./../src/components/auth/HamiResetPasswordCard.vue')['default']
    HamiRestPasswordCard: typeof import('./../src/components/auth/HamiRestPasswordCard.vue')['default']
    HeaderAvatar: typeof import('./../src/components/common/HeaderAvatar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
